### ISSUE TITLE
Uncaught ReferenceError: PasswordManager is not defined(…)

### ISSUE THREAD

**Issue by yuvilio** [megmage/chrome-export-passwords#1]
`Google Chrome 48.0.2535.0 dev` linux.

**Comment by megmage** [comment]
Hi!)
I tested new Chromium version - Version 48.0.2564.82 Built on 8.3, running on Debian 8.3 (64-bit) and test passed.

**Comment by lucadelu** [comment]
Hi, with Chromium version 51.0.2704.79 on 8.4, running on Debian 8.5 (64-bit) I get the same error

**Comment by ghost** [comment]
@lucadelu: `PasswordManager is not defined` shows when you have the wrong frame selected. You select the frame in combobox to the left of the _Preserve log_ checkbox. Make sure it is `settings(passwords)` and not something else.
